METAL_SHADER_LIB_NAME = cholesky
MAIN_SRC              = test_cholesky.cpp
LOCAL_INC             = -I/usr/local/include/eigen3
LOCAL_LIBS            = -lgsl
LOCAL_FRAMEWORKS      = -framework MetalPerformanceShaders

include ../common/common.mk
