METAL_SHADER_LIB_NAME = convolution_2d
MAIN_SRC              = test_convolution_2d.cpp
LOCAL_INC             = -Iciimage
LOCAL_OBJ_DIR         = ciimage
LOCAL_FRAMEWORKS      = -framework CoreImage -framework MetalPerformanceShaders

all:

include ../common/common.mk


